p8105_hw1_qs2261
================
Qinting Shen
2023-09-21

## Problem 1

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Now I will load the `early_january_weather` dataset.

``` r
data("early_january_weather")
```

- The `early_january_weather` dataset has the information about weather
  of the first half month of January in 2013 in EWR, which collected
  data including temperature, dewpoint, humid, wind_dirction,
  wind_speed, wind_gust, pressure, visibility, etc.

- There are 358 rows and 15 columns in the dataset.

- The mean temperature is 39.5821229 F.

Now I will make a scatterplot of `temp` and `time_hour`

``` r
ggplot(early_january_weather, aes(x = time_hour, y = temp, color = humid)) + geom_point()
```

![](p8105_hw1_qs2261_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

- This scatterplot indicates that the temperature fluctuated up and down
  every day, and the temperature shows an overall rising trend, reaching
  the highest temperature on the 14th. The humidity from Jan 11th to
  14th remained a high level (\>80).

save the scatterplot:

``` r
ggsave("scatterplot.pdf")
```

    ## Saving 7 x 5 in image

## Problem 2

create a dataframe, including

1.  `samp`: a random sample of size 10 from a standard Normal
    distribution
2.  `log_vec`: a logical vector indicating whether elements of the
    sample are greater than 0
3.  `char_vec`: a character vector of length 10
4.  `fac_vec`: a factor vector of length 10, with 3 different factor
    “levels”

``` r
hw1_df= tibble(
  samp = rnorm(10),
  log_vec = samp>0,
  char_vec = c ("A","B","C","D","E","F","G","H","I","J"),
  fac_vec = factor(c("small","medium","large","small","medium","large","small","medium","small","large"))
)
```

now take the mean of each variable:

``` r
mean(pull(hw1_df, samp))
```

    ## [1] 0.1053185

``` r
mean(pull(hw1_df, log_vec))
```

    ## [1] 0.5

``` r
mean(pull(hw1_df, char_vec))
```

    ## Warning in mean.default(pull(hw1_df, char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(hw1_df, fac_vec))
```

    ## Warning in mean.default(pull(hw1_df, fac_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

- when calculating the mean, random sample variable and logical vector
  works, while character and factor variable don’t work since they are
  not numeric or logical.

Write a code chunk that applies the `as.numeric` function to the
logical, character, and factor variables

``` r
as.numeric(pull(hw1_df,log_vec))
as.numeric(pull(hw1_df,char_vec))
```

    ## Warning: NAs introduced by coercion

``` r
as.numeric(pull(hw1_df,fac_vec))
```

- What happens, and why? Does this help explain what happens when you
  try to take the mean?

- I got a warning message saying NAs introduced by coercion when
  converting character_vector into numeric variable. This is because the
  character variable does not has a numeric value. Yes, this help
  explains why I got warning message when I tried to take the mean – the
  value of character_vector is NA. which cannot be calculated.
